### ISSUE TITLE
Is there a manual for cctrack?

### ISSUE THREAD

**Issue by daisy19880411** [cerfacs-globc/cyclone_tracking#1]
I am very interested in cctrack but can not handle it even though cctrack_tracking_products provides an example . Are there any references to show how cctrack tracks a cyclone (e. g., the criteria to define a cyclone)? Besides, is there a manual for cctrack (e.g., which parameters should be adjusted when used)?  thanks

**Comment by pagecp** [comment]
Hi, thanks for your interest in cctrack!

There is some documentation available: [https://meteocentre.com/cyclone-tracking/info_e.html](https://meteocentre.com/cyclone-tracking/info_e.html) and [https://meteocentre.com/cyclone-tracking/info_trop_e.html](https://meteocentre.com/cyclone-tracking/info_trop_e.html)

There is also a technical report but it is written in french unfortunately.

**Comment by daisy19880411** [comment]
> Hi, thanks for your interest in cctrack!
> 
> There is some documentation available: https://meteocentre.com/cyclone-tracking/info_e.html and https://meteocentre.com/cyclone-tracking/info_trop_e.html
> 
> There is also a technical report but it is written in french unfortunately.

Thanks for you replay.
I will turn to the paper by Sinclair.
